# Generated by Django 5.0.6 on 2024-07-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
