# Generated by Django 5.0.6 on 2024-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
